# =================================================================
#      Wazuh TLS Certificate Generation Configuration Template
# =================================================================
# This file defines the nodes within the Wazuh cluster for the
# purpose of generating internal TLS certificates.
# =================================================================

nodes:
  # --- Wazuh Indexer Node ---
  # This is the data store (OpenSearch).
  indexer:
    - name: ${WAZUH_INDEXER_HOSTNAME}
      ip: ${WAZUH_INDEXER_IP}

  # --- Graylog Server Node ---
  # This is the Graylog server. It MUST be included.
  server:
    - name: ${GRAYLOG_SERVER_HOSTNAME}
      ip: ${GRAYLOG_SERVER_IP}

  # --- Wazuh Dashboard Node ---
  # This is the web interface (OpenSearch Dashboards).
  dashboard:
    - name: ${WAZUH_DASHBOARD_HOSTNAME}
      ip: ${WAZUH_DASHBOARD_IP}
