{
 "title": "Sysmon - Network Connection Map",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "dst_ip",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule_group3:sysmon_event3",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "NETWORK CONNS-HISTOGRAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent_name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule_group3:sysmon_event3",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Destination Ips-GeoIP",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "data_win_eventdata_destinationIp_country_code",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "4", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" },
      {
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "source = wazuh-alerts-soc*\n| where isnotnull(dst_ip_country_code)\n| where rule_group3 = \"sysmon_event3\"\n| stats count() as EventCount by dst_ip_country_code\n| rename dst_ip_country_code as CountryCode\n",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Network Connections",
   "type": "netsage-sankey-panel",
   "gridPos": { "h": 26, "w": 13, "x": 11, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "src_ip",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "dst_ip",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "dst_port",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule_group3:sysmon_event3 AND NOT data_win_eventdata_sourceIp:fe*",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "PROCESSORS INFO",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 11, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "process_image",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "agent_name",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule_group3:sysmon_event3",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}