apiVersion: 1

datasources:
  - name: Wazuh
    type: grafana-opensearch-datasource
    access: proxy
    url: https://${WAZUH_INDEXER_IP}:9200
    isDefault: true
    editable: True

    basicAuth: true
    basicAuthUser: grafana
    secureJsonData:
      basicAuthPassword: ${GRAFANA_INDEXER_PASSWORD}

    jsonData:
      # OpenSearch flavor and version
      flavor: opensearch
      version: 2.13.1

      # Index settings
      database: wazuh-alerts-*
      timeField: timestamp

      # Concurrency and interval
      maxConcurrentShardRequests: 5
      interval: "No pattern"
      timeInterval: "10s"

      # Enable PPL queries
      pplEnabled: true

      # Logs view settings
      logMessageField: raw_description
      logLevelField: syslog_level

      # TLS settings (TLS enforced at URL; skipping verify avoids embedding CA here)
      tlsSkipVerify: true

      # Optional data links like in the screenshot
      dataLinks:
        - field: vulnerability.cve
          title: NVD
          url: https://nvd.nist.gov/vuln/detail/${__value.raw}
        - field: _id
          title: Open in Graylog
          url: https://${GRAYLOG_SERVER_HOSTNAME}:9000/explore?left=%5B%22now-6h%22,%22now%22,%22WAZUH%22,%7B%22refId%22:%22A%22,%22query%22:%22_id:%22,%22alias%22:%22%22,%22metrics%22:%5B%7B%22id%22:%221%22,%22type%22:%22logs%22,%22settings%22:%7B%22limit%22:%22500%22%7D%7D%5D,%22bucketAggs%22:%5B%5D,%22timeField%22:%22timestamp%22%7D%5D
